apiVersion: v1
kind: ServiceAccount
metadata:
    labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: aws-load-balancer-controller
    name: aws-load-balancer-controller
    namespace: kube-system
    annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::633458367150:role/eksctl-tfc-summit-addon-iamserviceaccount-ku-Role1-1C1LDENAG86PG
arn:aws:iam::633458367150:role/eksctl-tfc-summit-addon-iamserviceaccount-ku-Role1-1U8L2PIHFUN0P
arn:aws:iam::633458367150:role/eksctl-tfc-summit-cluster-ServiceRole-1F56PONMY3138
arn:aws:iam::633458367150:role/eksctl-tfc-summit-nodegroup-manag-NodeInstanceRole-AVVZMA50J8DN
arn:aws:iam::633458367150:role/eksctl-tfc-summit2-addon-iamserviceaccount-k-Role1-1JHK467V5KQTW
arn:aws:iam::633458367150:role/eksctl-tfc-summit2-cluster-ServiceRole-RWKQ9MFNSJME
arn:aws:iam::633458367150:role/eksctl-tfc-summit2-nodegroup-tfc-NodeInstanceRole-A0X9484WLQA7
