# // Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# // SPDX-License-Identifier: MIT-0

FROM 755674844232.dkr.ecr.us-east-1.amazonaws.com/notebook-spark/emr-6.5.0:latest

USER hadoop:hadoop

RUN python3 -m venv .env && source .env/bin/activate && \
    python3 -m pip install --upgrade pip && \
    python3 -m pip install --upgrade sagemaker
    
