apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: workshop
  namespace: karpenter
spec:
  provider:
    # instanceProfile: KarpenterNodeInstanceProfile-{EKSCLUSTER_NAME}
    launchTemplate: {EKSCLUSTER_NAME}-karpenter-launchtemplate
    subnetSelector:
      karpenter.sh/discovery: {EKSCLUSTER_NAME}
    securityGroupSelector:
      karpenter.sh/discovery: {EKSCLUSTER_NAME}
  labels:
    app: kspark
  requirements:
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
    - key: "kubernetes.io/arch" 
      operator: In
      values: ["amd64"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["c6a.large","c5.9xlarge","c5n.9xlarge","c6a.8xlarge","c6a.24xlarge","c6a.16xlarge","c6a.32xlarge","c5.xlarge","r5.xlarge","m5.xlarge"]  
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["{AWS_REGION}a"]

  limits:
    resources:
      cpu: 1000
      # memory: 1000Gi

  ttlSecondsAfterEmpty: 30