# // Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# // SPDX-License-Identifier: MIT-0
apiVersion: v1
kind: Pod
spec:
  # nodeSelector:
  #   app: sparktest
  volumes:
    - name: spark-local-dir-1
      hostPath:
        path: /local1  
    # - name: spark-local-dir-2
    #   hostPath:
    #     path: /local2  
    # - name: spark-local-dir-3
    #   hostPath:
    #     path: /local3
    # - name: spark-local-dir-4
    #   hostPath:
    #     path: /local4      
  initContainers:  
  - name: volume-permission
    image: public.ecr.aws/y4g4v0z7/busybox
    command: ['sh', '-c', 'mkdir /data1; chown -R 999:1000 /data*'] # grant volume access to hadoop user  
    volumeMounts:
      - name: spark-local-dir-1
        mountPath: /data1
      # - name: spark-local-dir-2
      #   mountPath: /data2
      # - name: spark-local-dir-3
      #   mountPath: /data3
      # - name: spark-local-dir-4
      #   mountPath: /data4 
  containers:
  - name: spark-kubernetes-executor
    volumeMounts:
      - name: spark-local-dir-1
        mountPath: /data1
      # - name: spark-local-dir-2
      #   mountPath: /data2
      # - name: spark-local-dir-3
      #   mountPath: /data3
      # - name: spark-local-dir-4
      #   mountPath: /data4 
  tolerations:
    - effect: NoSchedule
      key: node.kubernetes.io/not-ready
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/unreachable
      operator: Exists   