apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  namespace: emr
  labels:
    prometheus: "true"
  name: spark-driver-monitoring
spec:
  jobLabel: spark-driver-monitoring
  podMetricsEndpoints:
    - port: "web-ui"
      path: /metrics/executors/prometheus/
  selector:
    matchLabels:
      spark-role: driver
      emr-containers.amazonaws.com/resource.type: job.run

----
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: emr
  labels:
    prometheus: "true"
  name: spark-service-monitoring
spec:
  endpoints:
    - port: "web-ui"
      path: /metrics/driver/prometheus/
  selector:
    matchLabels:
      spark_role: driver
      emr-containers.amazonaws.com/resource.type: job.run